exports.command = function() {
  this
    .verify.elementPresent("table tbody")
    .verify.elementPresent("table tbody tr")

    .verify.elementPresent("table tbody tr .Patient_ID")
    .verify.elementPresent("table tbody tr .Sample_ID")
    .verify.elementPresent("table tbody tr .biopsy_site")
    .verify.elementPresent("table tbody tr .Enzalutamide")
    .verify.elementPresent("table tbody tr .Abiraterone")
    .verify.elementPresent("table tbody tr .site")
    .verify.elementPresent("table tbody tr .age")
    .verify.elementPresent("table tbody tr .Reason_for_Stopping_Treatment")
    .verify.elementPresent("table tbody tr .AR_Amplification_by_FISH")
    .verify.elementPresent("table tbody tr .Days_on_Study")
    .verify.elementPresent("table tbody tr .On_Study_Date")
    .verify.elementPresent("table tbody tr .Off_Study_Date")
    .verify.elementPresent("table tbody tr .abi_psa_response")
    .verify.elementPresent("table tbody tr .abi_radiographic_response")
    //.verify.elementPresent("table tbody tr .abi_reason_for_d/c")
    .verify.elementPresent("table tbody tr .enza_psa_response")
    .verify.elementPresent("table tbody tr .enza_radiographic_response")
    //.verify.elementPresent("table tbody tr .nza_reason_for_d/c")
    .verify.elementPresent("table tbody tr .prior_tissue")
    .verify.elementPresent("table tbody tr .when_where_stored")
    .verify.elementPresent("table tbody tr .biopsy_date")
    .verify.elementPresent("table tbody tr .steroid_at_time_of_biopsy")
    .verify.elementPresent("table tbody tr .steroid_stop_date")
    .verify.elementPresent("table tbody tr .sites_of_metastases_at_time_of_biopsy")
    .verify.elementPresent("table tbody tr .psa_at_biopsy")
    .verify.elementPresent("table tbody tr .ldh_at_biopsy")
    .verify.elementPresent("table tbody tr .alk_phos_at_biopsy")
    .verify.elementPresent("table tbody tr .hemoglobin_at_biopsy")
    .verify.elementPresent("table tbody tr .chga_at_biopsy")
    .verify.elementPresent("table tbody tr .nse_at_biopsy")
    .verify.elementPresent("table tbody tr .ecog_ps_at_biopsy")
    .verify.elementPresent("table tbody tr .gleason_grade")
    .verify.elementPresent("table tbody tr .orchiectomy")
    .verify.elementPresent("table tbody tr .psa_nadir_on_padt")
    .verify.elementPresent("table tbody tr .treatment_for_mcrpc_prior_to_biopsy")
    .verify.elementPresent("table tbody tr .post-biopsy_treatment")
    .verify.elementPresent("table tbody tr .psa_response")
    .verify.elementPresent("table tbody tr .radiographic_response")
    .verify.elementPresent("table tbody tr .death_or_last_contact")

  return this;
};
