exports.command = function() {
  this
    .verify.elementPresent("table")

    .verify.elementPresent("table thead")
    .verify.elementPresent("table thead tr")

    .verify.elementPresent("table thead tr .Patient_ID")
    .verify.elementPresent("table thead tr .Sample_ID")
    .verify.elementPresent("table thead tr .biopsy_site")
    .verify.elementPresent("table thead tr .Enzalutamide")
    .verify.elementPresent("table thead tr .Abiraterone")
    .verify.elementPresent("table thead tr .site")
    .verify.elementPresent("table thead tr .age")
    .verify.elementPresent("table thead tr .Reason_for_Stopping_Treatment")
    .verify.elementPresent("table thead tr .AR_Amplification_by_FISH")
    .verify.elementPresent("table thead tr .Days_on_Study")
    .verify.elementPresent("table thead tr .On_Study_Date")
    .verify.elementPresent("table thead tr .Off_Study_Date")
    .verify.elementPresent("table thead tr .abi_psa_response")
    .verify.elementPresent("table thead tr .abi_radiographic_response")
    //.verify.elementPresent("table thead tr .abi_reason_for_d/c")
    .verify.elementPresent("table thead tr .enza_psa_response")
    .verify.elementPresent("table thead tr .enza_radiographic_response")
    //.verify.elementPresent("table thead tr .nza_reason_for_d/c")
    .verify.elementPresent("table thead tr .prior_tissue")
    .verify.elementPresent("table thead tr .when_where_stored")
    .verify.elementPresent("table thead tr .biopsy_date")
    .verify.elementPresent("table thead tr .steroid_at_time_of_biopsy")
    .verify.elementPresent("table thead tr .steroid_stop_date")
    .verify.elementPresent("table thead tr .sites_of_metastases_at_time_of_biopsy")
    .verify.elementPresent("table thead tr .psa_at_biopsy")
    .verify.elementPresent("table thead tr .ldh_at_biopsy")
    .verify.elementPresent("table thead tr .alk_phos_at_biopsy")
    .verify.elementPresent("table thead tr .hemoglobin_at_biopsy")
    .verify.elementPresent("table thead tr .chga_at_biopsy")
    .verify.elementPresent("table thead tr .nse_at_biopsy")
    .verify.elementPresent("table thead tr .ecog_ps_at_biopsy")
    .verify.elementPresent("table thead tr .gleason_grade")
    .verify.elementPresent("table thead tr .orchiectomy")
    .verify.elementPresent("table thead tr .psa_nadir_on_padt")
    .verify.elementPresent("table thead tr .treatment_for_mcrpc_prior_to_biopsy")
    .verify.elementPresent("table thead tr .post-biopsy_treatment")
    .verify.elementPresent("table thead tr .psa_response")
    .verify.elementPresent("table thead tr .radiographic_response")
    .verify.elementPresent("table thead tr .death_or_last_contact")

  return this;
};
